# Generated by Django 5.0.1 on 2024-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homes_dateofbirth_homes_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='homes',
        ),
    ]
