# Generated by Django 5.0.1 on 2024-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_car_location_rentaltransaction_user_delete_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo1',
            field=models.ImageField(default='', upload_to='cars/images'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(default='', upload_to='cars/images'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(default='', upload_to='cars/images'),
        ),
    ]
