# Generated by Django 5.0.1 on 2024-03-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
