# Generated by Django 5.0.1 on 2024-03-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
    ]
