# Generated by Django 5.0.1 on 2024-03-26 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_profile_is_active_remove_profile_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaltransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
