# Generated by Django 5.0.1 on 2024-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_rentaltransaction_user_remove_car_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='', upload_to='cars/images'),
        ),
    ]
