# Generated by Django 5.0.3 on 2024-03-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_car_car_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='locations',
            field=models.ManyToManyField(related_name='cars', to='home.location'),
        ),
    ]
