# Generated by Django 5.0.3 on 2024-03-29 17:45

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_images',
        ),
        migrations.AddField(
            model_name='car',
            name='car_image_primary',
            field=models.ImageField(default='', upload_to=home.models.car_image_path),
        ),
        migrations.AddField(
            model_name='car',
            name='car_image_secondary1',
            field=models.ImageField(blank=True, upload_to=home.models.car_image_path),
        ),
        migrations.AddField(
            model_name='car',
            name='car_image_secondary2',
            field=models.ImageField(blank=True, upload_to=home.models.car_image_path),
        ),
    ]
